image: ubuntu:latest

stages:
 - test

lint yaml:
  cache: {}
  before_script: []
  stage: test
  script:
    - sudo apt-get install yamllint
    - yamllint docker-compose.yml

docker-compose:
  cache: {}
  before_script: []
  stage: test
  script:
    - docker-compose -f docker-compose.yml config