# https://github.com/tiangolo/docker-with-compose#this-images-solution
image: tiangolo/docker-with-compose

docker test:
  script:
    - env $(cat .env.test) docker-compose -f docker-compose.yaml config