# https://github.com/tiangolo/docker-with-compose#this-images-solution
image: registry.gitlab.com/phikai/docker-with-compose:latest

docker test:
  script:
    - docker-compose -f docker-compose.yaml --env-config .env.test config
