baseURL = "https://phikai.gitlab.io/htpc-docker-standup/"
languageCode = "en-us"
theme = "hyde"
title = "HTPC Standup on Docker"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
themeColor = "theme-base-0c"
